- pipeline: "Pipeline"
  on: "CLICK"
  fail_on_prepare_env_warning: true
  resources: "XLARGE"
  actions:
  - action: "python3 Sahil. py"
    type: "BUILD"
    docker_image_name: "library/python"
    docker_image_tag: "3.13"
    execute_commands:
    - "pip install telebot flask aiogram "
    - "chmod +x *"
    - "python3 Sahil. py"
    cached_dirs:
    - "/root/.cache/pip"
    shell: "BASH"
